#!/bin/bash

#nom: cherifi
#prenom: aouakas



number='^[0-9]+$'

#etape1 verifier le nombre de parametre

if test $# -lt 4 ; then

 echo "----veuillez entrer tout les arguments et respecter l'ordre (user ip mdp port)------"

 exit 1

fi

#etape2: verifier si le numero de port saisie est un nombre valable

if !  [[ $4 =~ $number ]]; then

        echo  "veuillez saisir un numero de port valide" 
	exit 2
fi

#etape verfier la connexion avec la machine souhaité

 ping -q -c1 $2 > /dev/null

if [[ $? -eq 1 ]] ; then

        echo "-------------- pas de connection avec $2 ------------- "


else
	 echo "-------------- liste des machine qui connecté a $2 ----------" ;
              echo w | sshpass -p $3 ssh $1@$2 -p $4 | tail -1;

#	   echo sshpass -p $3  ssh $1@$2 "w" | tail -1

exit 3

fi
