#!/bin/bash

echo  ""la liste des fichier qui sont en lecture dans le repertoire etc""

liste=`ls /etc`
#echo $liste

#stat=`stat -c %y $i`

for i in $liste ; do
         if [ -r /$i ]; then
		 echo "$i"
         fi
done


echo  "la liste des fichier qui sont en ecriture dans le repertoire etc"

for i in $liste ; do
         if [  -w /$i ]; then
                echo $i
	 fi
done

