#!/bin/bash

#nom: cherifi
#prenom:aouakas


number='^[0-9]+$'  

for (( i=0 ;  i<=10 ; i++ ));  do
	
if  ! [[ $1 =~ $number ]] ; then

	echo "veuillez entrer un nombre entier please!" >&2; exit 1
else
	 echo $1*$i = $(($1*$i))
fi
done
